### ISSUE TITLE
Add CC Korea team members to github

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/global-summit-#14]

**Comment by mattl** [comment]
You'll need to let me know all their usernames

**Comment by soohyunpae** [comment]
I'm collecting them now. Will let you know tomorrow.

**Comment by soohyunpae** [comment]
@mattl Can you add the following: dalcomnews@gmail.com (username: nanshil), hskang211@gmail.com

**Comment by mattl** [comment]
Can you tell me everyone's usernames? If they don't have one, they need to register :)

**Comment by soohyunpae** [comment]
It's jenniferkang for hskang211@gmail.com. Thanks! :)

**Comment by soohyunpae** [comment]
@mattl, can you add jenniferkang and nanshil to this repository?
