### ISSUE TITLE
summit.creativecommons.org/kr

### ISSUE THREAD

**Issue by mozodev** [creativecommons/global-summit-#23]
Hello, 
I'm Hong, developer, CCKorea team.
This is my first time that I write issue at creativecommons. :)

repository:
http://github.com/creativecommonskorea/2015-summit

temporary domain:
http://summit.cckorea.org

I've just finished up korean landing page. 
I'm afraid whether I shoud pull request for those codes to www/summit/kr, 
or maybe would it be enough that I just send _site.zip to matt?

Please let me know what you think.

**Comment by mattl** [comment]
Please send a pull request :)

**Comment by mozodev** [comment]
I tested on local but there were no special issues.
Please review my PR #24

**Comment by mattl** [comment]
So I've accepted this PR. We need to fix a few things, mostly around how bootstrap and jquery are loaded. We should load these from CDN instead of serving them locally. 

```
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>

 <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> 
```

**Comment by mattl** [comment]
Thanks @mozodev

**Comment by mozodev** [comment]
@mattl You're welcome. :smile:
