### ISSUE TITLE
keynote invite followups from Ryan

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#29]

**Comment by ryanmerkley** [comment]
Update:
- Kahn requires speaker form to be filled out. Asked Board members if they have direct contact. 
- CC Korea approaching Benkler directly (he's otherwise away to June 21).

**Comment by soohyunpae** [comment]
We're about to reach Benkler and wondering what is the key information that should be included in the email in addition to the dates and location (aiming to send it by this weekend).

Can we say that we will provide business class round-trip flights, hotel, and a small travel stipend for local travel expenses?

**Comment by tvol** [comment]
IMO we should try to be a position to offer something like that. I assume he would likely expect it, and hopefully wouldn't also want an honorarium for the talk itself.
