### ISSUE TITLE
offer other options for submitting proposals for GS sessions?

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#34]
Pratham Books wants an offline document to download and submit a proposal for GS programming

**Comment by mattl** [comment]
I'd suggest we just allow people to email a submission and then we enter it into the system ourselves. Anything more than that seems like overkill. Presumably they're okay submitting a document by email, and don't intend to mail/fax.

**Comment by tvol** [comment]
@mattl yes i think that's fine. Do you want me to dump the info on https://donate.creativecommons.org/civicrm/event/register?reset=1&id=12 into a .doc and .odt and then you upload those with a short note about which email they should send in the completed doc?

**Comment by mattl** [comment]
Let's just make it a page on the website, they can copy that into an email,
complete it offline? Submitting it in an office document is going to
invariably lead to adding things we can't add to the form, like images or
other attachments.

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by tvol** [comment]
@mattl :+1:

**Comment by mattl** [comment]
https://summit.creativecommons.org/cfp-offline/

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by tvol** [comment]
looks fine. thanks. @mattl do you want to put a teeny tiny mention of that on the normal page at the bottom, or just dole out the offline URL to those who ask?

**Comment by mattl** [comment]
Give them the URL if they ask, and be sure to point out that the Date for
offline submissions is July 7th.

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by tvol** [comment]
@mattl why 7 july?

**Comment by mattl** [comment]
To give us time to get them all in the system with the rest.

**Comment by tvol** [comment]
ok
