### ISSUE TITLE
registration fee notice

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/global-summit-#35]
Can we add a notice that current early-bird fee is only available until Aug 23 and the fee will go up to 100/70 from Aug 24 to the text on the registration page? We could perhaps include timezone information (is it UTC or Pacific Time?) so that people know the exact deadline regardless of their location.
https://donate.creativecommons.org/civicrm/event/info?reset=1&id=11

@jessicacoates What do you think?

**Comment by mattl** [comment]
There's no exact deadline.

**Comment by tvol** [comment]
@mattl should we then remove the date from the keynote announcement blog post?

**Comment by mattl** [comment]
No, I mean it'll happen on the 23rd... but it's a "sometime that day thing"

**Comment by tvol** [comment]
@mattl duly noted.
