### ISSUE TITLE
Access to Global Summit CFP Submissions

### ISSUE THREAD

**Issue by pgstacey** [creativecommons/global-summit-#37]
I need to see the proposals that are being submitted in response to our Global Summit call for participation / proposals.
Please let me know how to get access. Thanks.

**Comment by mattl** [comment]
https://donate.creativecommons.org/civicrm/event/search?reset=1&force=1&status=true&event=12

**Comment by pgstacey** [comment]
Clicked on link. Get the following message:
"Access denied
You are not authorized to access this page."

**Comment by mattl** [comment]
Try http://donate.creativecommons.org/user first.

If you don't have a Civi login, let me know and we'll make you one.

---

Matt Lee
Creative Commons
Boston, MA, USA

**Comment by pgstacey** [comment]
I don't have a Civi login.

**Comment by peterspdx** [comment]
I think everyone on the committee that will be reviewing proposals per Jess' latest email should get access before our upcoming meeting.  Or if that's not advisable, is there a way to replicate or send proposals ALSO to another location that's easy to access.

**Comment by pgstacey** [comment]
Matt, welcome a one on one to discuss options related to my request and Diane's - which are actually different requests, at least the way I'm thinking about the process. Lets chat about process and figure best way forward.

**Comment by jessicacoates** [comment]
I'd actually vote that the committee members, or at least the affiliate ones, don't get access the proposals until the CfP has closed. That way they are all on the same footing, and people won't start thinking of scores etc until everything is in.

Once they are in, we can either give the committee members access to them online or we can download them all into an external document and give them access there. My memory was it wasn't too hard to download them last time. Either way, I'm thinking we'll probably get them to score them on a google doc - but they can read the submissions anywhere. 

Matt/Rob - are you happy with giving 10+ affiliates Civi logins? What do others think?

**Comment by pgstacey** [comment]
I'm in accord with Jessica. I'm interested in seeing the submissions for rough numbers and an overall sense of the kind of thing coming in but I wasn't thinking all committee members would get access to all the proposals as they come in. To keep the playing field level I believe its better to review them all at the end, after the deadline for submission. Lets discuss this during the Program Selection Committee meeting tomorrow.

In addition I wasn't necessarily thinking the review process would happen in Civi. But I want to see what it possible and understand the process involved in using Civi or exporting out of Civi to some other place - perhaps a Google doc as Jess suggests. 

I'll work with our technical team on options and report back to the Program Selection Committee.

**Comment by soohyunpae** [comment]
I also agree with Jess and Paul that it's better to keep proposals away from the committee members until the submission process is closed, for the sake of fairness; whereas, I think access to proposals would be useful to the program committee leads -  i.e. Paul, Jess, and me - and probably some of the Steering Committee.

I don't have particular opinion about the format - either Civi or Google doc is fine, as long as it's less burdensome to the tech team and to those who will use it. :)

**Comment by mattl** [comment]
So, I suggest making a Civi login for Paul, and when CFP closes, I will export things from Civi into a spreadsheet, remove any personal information and share. I can't give a Civi account to anyone who's not a CC staff member as Civi contains personal information, donor information, etc.

**Comment by peterspdx** [comment]
+1 to Mattl's suggestion.  All sounds right re data, not having pre-evaluation access, and similar.  Though I think it would have been helpful for staff to have access to some in advance rather than have blind submissions that likely overlap.  Especially now that I'm on this programming call where it's "top priority" get chosen and then it's up to the "winning leader" to identify and then work with others who submitted similar proposals.  But I can live with this.

**Comment by mattl** [comment]
As mentioned previously, I can also have the CFP form (aka profile) send an email when it is completed, so I could have future submissions go to an alias for Paul/Jess/SooHyun too, if that's useful

**Comment by pgstacey** [comment]
Diane, from a process point of view we've simply been following the process used for previous summits. Interesting to hear your suggestions for alternative process. I'm open to hearing any other recommendations you have on process - perhaps its best to send them to me directly. I hear what you are saying about the opportunities for matchmaking proposals that overlap. I'm glad you can live with doing that as part of the proposal evaluation and selection process. 

Matt, agree with your suggestion:
-  make a Civi login for me - thank you.
- when CFP closes, export all proposals from Civi into a spreadsheet, remove any personal information and share. Sounds great this is similar to past practice and expect we'll use the evaluation form and criteria from previous summits
- welcome input from Jess/SooHyun as to whether they want to receive an e-mail from Civi everytime the CFP form is completed - or to an alias

**Comment by soohyunpae** [comment]
Exporting proposals from Civi into a spreadsheet sounds good to me too.

I would love to receive alert emails for future submissions but more importantly access to the whole list of proposals submitted so far would be really helpful for me in planning things from my end.

**Comment by mattl** [comment]
Future submissions will come via email. I'll email you what we have so far.
