### ISSUE TITLE
blog post highlighting keynotes

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#42]

**Comment by tvol** [comment]
- first confirm all are finalized
- even if we don't have which days they'll be speaking at this point its fine
- give heads up to rebecca to see if there's anything we can work in to donor outreach regarding the summit keynote announcement
- give heads up to CC-affiliates before the blog post is published
- also get text on the CC summit website

**Comment by soohyunpae** [comment]
Can you please give heads up to me as well so that I can publicize it locally around the same time?

**Comment by tvol** [comment]
draft at https://docs.google.com/document/d/1xFgQGKzexRAKXxBL2kf7a9i8eOuBL7UtPy4PVPDRDLE/edit

**Comment by tvol** [comment]
it is ready for publishing tomorrow or wed https://creativecommons.org/?p=45830&preview=true

**Comment by tvol** [comment]
done https://creativecommons.org/weblog/entry/45830
