### ISSUE TITLE
blog post announcing summit schedule with session highlights

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#43]

**Comment by tvol** [comment]
draft https://docs.google.com/document/d/1dYXwItGVVvnuYncmI8RRyQoPJgHMHzAd5asjVVsST40/edit
- the sched.org should be shared with affiliates before we post publicly on the CC website
- the blog post will be published on cc website thursday, 10 september. 
- social media cc twitter and facebook
- add link to it on the Global Summit Facebook page
- coordinating announcement with soohyun and jennifer from CC Korea

**Comment by rebeccakross** [comment]
Triple confirming that we are coordinating the public announcement with our
sponsor page updates. If for any reason this poses a challenge, _please let
me know in advance of public announcement_ so that I can help troubleshoot
and/or communicate with our sponsors as needed.

**Comment by tvol** [comment]
@rebeccalendl yes please add the relevant information to the blog post draft. what else needs to be done? is @mattl adding the sponsor info to the summit page at https://summit.creativecommons.org/sponsorship/?

**Comment by mattl** [comment]
Different page but yes.

**Comment by tvol** [comment]
@mattl @rebeccalendl ok

**Comment by tvol** [comment]
@rebeccalendl is there anyone else we want to thank specifically in the blog post? or do we want to also point to the sponsor page that @mattl is setting up?

**Comment by rebeccakross** [comment]
4 spots: blog post, summit site, sched site, cc site. Matt and I are in touch about it, just want to make sure the timing is all synched up  thanks for the attention to this, super helpful.
