### ISSUE TITLE
Registration Name Field

### ISSUE THREAD

**Issue by jessicacoates** [creativecommons/global-summit-#46]
I'm having difficulty tracking down/working with the name field on the registration form.

I've been downloading the registrations so I can create a list to share with the RCs, but I can't work out where the "name" field ends up. I realised quickly it didn't go into First or Last Name. Under Sort Name most of them are email addresses. I thought I'd solved the problem by using Nickname, but a lot of them are still informal eg "Phil" or "Nina".

Am I missing where their entry is ending up, or are they entering informal names? Any way we can get a formal name for all registrants?

**Comment by jessicacoates** [comment]
Same with the CFP registration - where are the names ending up?

**Comment by mattl** [comment]
So rather than having a first name field, we have a name field. This is
best practice, as not all cultures have a concept of first name like we'd
use it in the USA.

**Comment by jessicacoates** [comment]
Yes - I'm fine with that. I'm not objecting to the form at all - what I'm having difficulty with is accessing the information they put in the name field. Where does it end up? 

I've tried exporting all the primary fields, and I've tried going through and selecting specific fields, but I still haven't managed to create a list of the names of everyone submitting. I can see on the form that the field is listed as being under categorised under "contacts" but when I try to export and go to "Select Fields" I can't find "contacts" as a category. 

But trying other similar fields doesn't work - under "Sort Name" most of them come up as an email. Under "Nickname" you still get a fair number of informal names, like "tom" and "Nina". I'm sure that people aren't putting these things into the "name" field - I'm sure that somewhere on CiviCRM there's a list that links the person's full name with their registration/submission. But where?

**Comment by mattl** [comment]
Did this get figured out?

**Comment by jessicacoates** [comment]
Not by me - any idea where their names are ending up?

**Comment by mattl** [comment]
It looks like not everyone has entered a name in a name field, but may be listed in a speaker field.
