### ISSUE TITLE
social media announce of winner of logo competition July 23

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#47]

**Comment by soohyunpae** [comment]
@tvol the announcement is now live on the logo website. https://logo.cckorea.org Can you please do social media announcement? I'm contacting the winner and will follow up if there are more updates - it might be worth to do a short blog post to wrap up the project and recognize the winner, I think. What do you think, @jessicacoates?

**Comment by tvol** [comment]
ok i'll share over twitter and facebook

**Comment by tvol** [comment]
@soohyunpae @jessicacoates I think we might want to avoid a blog post at this time because we've asked for changes to the final design from the artist.

**Comment by mattl** [comment]
@soohyunpae can you email me the high res logo?
