### ISSUE TITLE
Create planning document

### ISSUE THREAD

**Issue by jessicacoates** [creativecommons/global-summit-#5]
CC Korea responsible

**Comment by soohyunpae** [comment]
Working on it. Will share it by today (Seoul time).

**Comment by soohyunpae** [comment]
Done.
https://docs.google.com/a/creativecommons.org/spreadsheets/d/1LgwK-nbym3-ZowWL9rQ4u9jrl22wcZ9NFi0iVJMwLbg/edit#gid=9
