### ISSUE TITLE
Name field input missing from Registration data

### ISSUE THREAD

**Issue by jessicacoates** [creativecommons/global-summit-#50]
This is the same issue as the CFP - whatever people are putting the "name" field isn't appearing in the data you can access under the event on Civi.

They can't be skipping the field - it's compulsory. Plus I would find it very odd if people were skipping the name field in registration. 

It's really important we find this data - we need to know who is registered for the event.

If we can't find the data we at a minimum need to change the form so that we have the name of future registrants.

**Comment by mattl** [comment]
The names are there, happy to show you how to export whatever data you need from Civi. I just did a test and was able to get names, email addresses, visa requirements, etc.

**Comment by jessicacoates** [comment]
Yup - can you show me how to get the names? I still can't find a way to extract them. 

I'm using the export function on the page below, and I still get about half of them coming up as email addresses (like the sort name). I've tried exporting primary contacts and choosing specific fields (is there one I'm missing?).

https://donate.creativecommons.org/civicrm/event/search?reset=1&force=1&status=true&event=11

**Comment by mattl** [comment]
Export Individual>Nickname. Try that?

**Comment by jessicacoates** [comment]
Solves the email problem, but you still end up with a lot of single names (eg keeno, tav), numbers etc. 

Do we think this is what people are putting in the name field? It just seems odd for so many people not put in their full name when they're registering.

**Comment by mattl** [comment]
The names are there. Let me know what you want and I'll export tomorrow.

**Comment by jessicacoates** [comment]
Just a list of the names that is associated with any other major field (eg their email) so I can align it with the list I've downloaded.

Let me know how you did it too, so hopefully I can replicate it and not have to bother you again.
