### ISSUE TITLE
Update https://summit.creativecommons.org/sponsorship/

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/global-summit-#57]
Retitle this page "Sponsors" and update content to serve as a thank you page to sponsors

Header: Thank You to CC 2015 Global Summit Sponsors

Include logo listing with website link by sponsorship amount. I'll send logos and recognition levels over via email. For logos that haven't come in yet, please use written name with website link as a placeholder.

**Comment by rebeccakross** [comment]
Links to a few here, sending zip file via email (can't seem to get it to upload here)
https://drive.google.com/open?id=0B2mMwngN_OW2NU1zMEdWUmtraXM
https://www.mozilla.org/en-US/styleguide/identity/mozilla/branding/
https://drive.google.com/folderview?id=0B2mMwngN_OW2NU1zMEdWUmtraXM&usp=drive_web

**Comment by rebeccakross** [comment]
@mattl Add MacArthur logo with link at 25k level in three places: 1) summit site and 2) Sched site, and 3) CC supporters page.

**Comment by soohyunpae** [comment]
@rebeccalendl @mattl Can you point me to where I can get the AI files of the logos? We need them for printed materials.

**Comment by mattl** [comment]
@soohyunpae We don't work with AI files, only SVG and we have no vector versions of any of these logos.

**Comment by tvol** [comment]
@soohyunpae you can likely find relatively large .png or .jpgs of these on the web

**Comment by rebeccakross** [comment]
@mattl will you please add MacArthur logo with link at platinum 25k level in three places: 1) summit site and 2) Sched site, and 3) CC supporters page.

@mattl will you please also add Lumen logo with link at bronze 2.5k level in three places: 1) summit site and 2) Sched site, and 3) CC supporters page.
![lumenlogo400x140](https://cloud.githubusercontent.com/assets/13322149/10106290/ac6b8186-6368-11e5-9086-d252e59f74b6.png)

**Comment by rheaplex** [comment]
Logos added to summit (@mattl, the changes are in the repo), cc and sched.

Any fixes let me know.
