### ISSUE TITLE
embed Sched into CC summit website 

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#58]
https://creativecommonsglobalsummit2015.sched.org/

**Comment by mattl** [comment]
Can you add me and Rob as admins on the Sched account?

**Comment by tvol** [comment]
@mattl done

**Comment by pgstacey** [comment]
Matt, do you guys have everything you need to do this embed? Looks like the instructions in Sched.org are pretty straightforward. I'm hoping we can make it public on Thursday? Sequence of events as I see them are:
- Jess sends letters to successful and unsuccessful submitters about whether they made it into the program - hopefully today.
- we send sched.org to affiliates for early viewing - hopefully today.
- tomorrow Thursday we embed sched.org in our global summit web site.
- tomorrow Thursday we publish a blog post saying program is now public - but subject to change

Thought I'd try and coordinate this and make sure you guys are good to go on your end.

**Comment by mattl** [comment]
Yeah, there's a new homepage coming tomorrow with a big focus on the event,
and the sponsors and schedule pages will be up on the summit website.

---

Matt Lee
Creative Commons
Boston, MA, USA
