### ISSUE TITLE
Create detailed budget

### ISSUE THREAD

**Issue by jessicacoates** [creativecommons/global-summit-#6]
CC Korea responsible for first draft

**Comment by soohyunpae** [comment]
Working on it. Will share it by today (Seoul time).

**Comment by soohyunpae** [comment]
Created. Working on details in consultation w/ Ryan.
https://docs.google.com/a/creativecommons.org/spreadsheet/ccc?key=0Ason8kkrB_x9dFVtSHRZank5dDYwR1k4Q1B2eWI4WFE#gid=0

@jessicacoates We're trying to put everything that might or might not happen into this. Feel free to edit it and let me know if you have any feedback!

**Comment by soohyunpae** [comment]
Shared final estimated budget.
