### ISSUE TITLE
get info on keynote video streaming

### ISSUE THREAD

**Issue by tvol** [creativecommons/global-summit-#64]
@soohyunpae do you have more details on this, like what platform will be used and if there is a URL where it will be available?

**Comment by rebeccakross** [comment]
@mattl on yesterdays global summit call we discussed options for promoting live video streaming in advance via the cc and/or summit website, and potentially using the opportunity to invite people to sign up in advance with an email address and be notified when the live streaming of each keynote starts. please advise on feasibility and if you have recommendations on how you'd like to do this, or I am happy to make suggestions if that would be preferred.

**Comment by mattl** [comment]
What do we know about the live streaming setup?

**Comment by rebeccakross** [comment]
@soohyunpae is getting back with details, we discussed wanting to begin promoting a URL as soon as something is available so will hope to hear more shortly

**Comment by mattl** [comment]
We need to consider that not everyone will be okay with their talk being
streamed, that talks are under different licenses, etc.

I'll wait for more details before we can figure out the next steps.

**Comment by soohyunpae** [comment]
Our team is planning to record and live stream (the main auditorium and the seminar room on Oct 15 and the main auditorium and the small auditorium on Oct 16) on our youtube channel. But if you have better suggestions, let me know.
And we will need to ask speakers' approval in advance, of course.

**Comment by mattl** [comment]
YouTube is probably fine for the live stream. I'd suggest Vimeo for the
recordings as they support the full range of licenses.

**Comment by rebeccakross** [comment]
@mattl Based on this info, is there any way for us to do advance outreach and list building around this (ie. worth setting up an email sign up and then sending out a 'join us - live stream starts now' kind of thing)?

**Comment by rebeccakross** [comment]
@robmyers here's the info on live streaming, is this enough to run with? if not we need to ping korea team for more details.

**Comment by rheaplex** [comment]
@rebeccalendl Please can we ping Korea for details.

**Comment by rebeccakross** [comment]
will do. what specifically do we need? a URL? anything additional?

**Comment by rheaplex** [comment]
A URL is the main thing. If they're using a service other than one of the big obvious ones then any registration details or browser requirements would be useful.

Thank you.

**Comment by rebeccakross** [comment]
@soohyunpae can we get a few more details on the live streaming so we can do some outreach? A URL is the main thing we'd need, or any platform registration details or browser requirements would be useful too if applicable.

**Comment by soohyunpae** [comment]
As I said earlier, we're using Youtube for the live streaming. So two URLs for each day. But I think we won't have the URLs until we have set things up on site. @mozodev

**Comment by rheaplex** [comment]
Do you have a landing page for the streams? We'd like to be able to promote
a URL for people who want to watch remotely.

**Comment by ryanmerkley** [comment]
Suggestion: Set up a static page at https://summit.creativecommons.org/livestream with copy that says something like: "The CC Global Summit live stream from Seoul, Korea will be available here starting on X date at X time. Please join us then. We will post a schedule of streaming talks as it becomes available." 

Plan to embed the CC Korea youtube stream there. We can then start promoting this URL. 

Time is getting short, and Rebecca needs this for promotion to our lists. Can we get it set up today?

**Comment by rheaplex** [comment]
I have added the page -

https://summit.creativecommons.org/streaming/

I will add the link to the email.

**Comment by mozodev** [comment]
Hi, here are live stream info:

```
1. 2015/10/15 01:00 (UTC)
National Museum of Korea Main Auditorium

CC SUMMIT Day 1: Celebration of Sharing (Open ReMark, Track1,3, Keynote)
https://www.youtube.com/watch?v=IhQfOSSV9yM

2. 2015/10/15 4:30 (UTC)
National Museum of Korea Lecture Room

CC SUMMIT Day 1: Celebration of Sharing WEB CAST (Track 2, 4)
https://www.youtube.com/watch?v=adxnw7Kcpfc


3. 2015/10/16 1:00 (UTC)
National Museum of Korea Main Auditorium

CC SUMMIT Day 2: Work of Sharing (Openremark, Keynote, showcases of sharing)
https://www.youtube.com/watch?v=yORNjoDTHcE

4. 2015/10/16 2:00 (UTC)
National Museum of Korea Small Auditorium

CC SUMMIT Day 2: Work of Sharing WEBCAST([Fair use and business] Jay Yoon_Project Lead, CC Korea)
https://www.youtube.com/watch?v=RWUjhcVBjHo
```

**Comment by rheaplex** [comment]
Thank you! I've added the details, slightly reformatted, here -

https://summit.creativecommons.org/streaming/

**Comment by mozodev** [comment]
I know this is insane... live stream url changed.

```
CC SUMMIT Day 1: Celebration of Sharing (Open ReMark, Track1,3, Keynote)
https://www.youtube.com/watch?v=IhQfOSSV9yM 
=>
https://www.youtube.com/watch?v=0gymWQg6kN8
```
