### ISSUE TITLE
Close online registration

### ISSUE THREAD

**Issue by soohyunpae** [creativecommons/global-summit-#65]
@mattl @robmyers can we close the online registration on Friday Oct 9, considering travel time? For Korean website, we are closing the online registration on Monday Oct 12 and will give an advance notice and do a social media. And people who want to register after that can do so on site in Seoul using credit card or cash.

@tvol @mmoreshead

**Comment by rheaplex** [comment]
@soohyunpae Yes I'll close this Friday afternoon PST.

**Comment by rheaplex** [comment]
I've removed the link from the current version of summit.creativecommons.org, I'll turn off registration in civicrm later.
