### ISSUE TITLE
Video of PIA talk?

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/global-summit-#67]
Possible to clip Rick Falkvinge's 5 min vid for me to send to PIA?

**Comment by mattl** [comment]
Sure. Do you have the original and roughly when it starts?

**Comment by rebeccakross** [comment]
Thank you. I don't...should be with the recordings from day one, he went first or second I think so right off the bat

**Comment by mattl** [comment]
Does this need to go up on the website somewhere?

**Comment by mattl** [comment]
https://vimeo.com/creativecommonsvideos/review/145690763/d012e63f3b

**Comment by rebeccakross** [comment]
This is great, thx. Doesn't need to go anywhere, just wanted to get them a copy per their request.
