### ISSUE TITLE
Video of Ryan's keynote?

### ISSUE THREAD

**Issue by rebeccakross** [creativecommons/global-summit-#68]
Possible to cut and post on Vimeo with label "Creative Commons' CEO Ryan Merkley's 2015 Global Summit keynote" and share link?

**Comment by mattl** [comment]
When do you need this by? If you can tell me the day and time in the video
that he speaks...

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccakross** [comment]
By Friday would be great. Day 2 AM.

**Comment by mattl** [comment]
I probably can't get it done by then, I have a bunch of other things.

Also an actual start time for the part in question would be useful,
otherwise I'm spending time looking for it.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by rebeccakross** [comment]
Starts with intro by Paul Brest at 38:30 
https://www.youtube.com/watch?v=RWUjhcVBjHo

**Comment by mattl** [comment]
Great, that helps a lot.

---

Matt Lee
Creative Commons
Austin, TX, USA
3pm-11pm UTC

**Comment by jenniferkang** [comment]
Ryan Keynote
https://www.youtube.com/watch?v=qTDMCsfdHkI

All Video
https://www.youtube.com/user/CreativeCommonsKorea/feed
-  Jennifer / CCKOREA -

2015-11-19 8:46 GMT+09:00 Matt Lee notifications@github.com:

> Great, that helps a lot.
> 
> ---
> 
> Matt Lee
> Creative Commons
> Austin, TX, USA
> 3pm-11pm UTC
> 
> On Wed, Nov 18, 2015 at 5:40 PM, rebeccalendl notifications@github.com
> wrote:
> 
> > Starts with intro by Paul Brest at 38:30
> > https://www.youtube.com/watch?v=RWUjhcVBjHo
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/creativecommons/global-summit-/issues/68#issuecomment-157899770
> > 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/creativecommons/global-summit-/issues/68#issuecomment-157900730
> .

## 

_강현숙  *Jennifer Kang_[image: cckorea_logo3.png]*

 CCKOREA | 사무국장

_Twitter @hskang      Tel_ 070-7618-0321

hskang211@gmail.com

_Address *_마포구 서교동 363-20 5층 \* (오시는길
http://map.naver.com/?dlevel=12&pinType=site&pinId=12231010&x=126.9218731&y=37.5511880&enc=b64
)

_Sites  CCKOREA_ (cc http://cckorea.org/korea.org http://cckorea.org/)*
공유허브 _(_sharehub.kr http://sharehub.kr/_)  *코드나무 *(_codenamu.org
http://codenamu.org/*)

**Comment by rebeccakross** [comment]
Yep, got it. Thanks!
